from .numberplate_ocr_data_module import OcrNetDataModule
from .numberplate_inverse_data_module import InverseNetDataModule
from .numberplate_orientation_data_module import OrientationDataModule
from .numberplate_options_data_module import OptionsNetDataModule
