name: "su_text_detector"
max_batch_size : 0
platform: "tensorflow_savedmodel"
input [
  {
    name: "the_input_su"
    data_type: TYPE_FP32
    dims: [-1, 128, 64, 1]
  }
]
output [
  {
    name: "softmax_su"
    data_type: TYPE_FP32
    dims: [-1, 32, 40]
  }
]