name: "craft_refine_net"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "refine_input"
    data_type: TYPE_FP32
    dims: [-1, -1, -1, 2]
  },
  {
    name: "refine_feature"
    data_type: TYPE_FP32
    dims: [-1, 32, -1, -1]
  }
]
output [
  {
    name: "refine_output"
    data_type: TYPE_FP32
    dims: [-1,-1,-1,1]
  }
]